### PR TITLE
UI: Scrollbar for preview and results tables

### PR DESCRIPTION
**Pull request by xgaia**
- [x] Scrollbar on preview tables
- [x] Scrollbar on results table
- [x] executable testAskomics.sh

Before

selection_007

After 

selection_008

### CODE REVIEW

**Comment by xgaia** [comment]
Don't merge now please, I will apply same css for the results table: 

selection_009

**Comment by xgaia** [comment]
I don't succeed to make a beautiful results table. If a put this css properties:
```css
.table-results {
   width: auto;
   display: inline-block;
   overflow-x: auto;
}
```

The table with inline-block is ugly when there is only few attributes selected:

selection_010
but it is ok when there is a lot of attributes with long strings 

selection_013

**Comment by ofilangi** [comment]
when you put min-width next wifth=auto don't resolve the problem ? it may overload width...

**Comment by xgaia** [comment]
Ok its fixed now. i put the overflow-x in the parent <div> of the table.

**Pull request merged**
