### PR TITLE
[WIP] Transitioning frontend to TypeScript / webpack

### PR DESCRIPTION
**Pull request by Piezoid**
Hi !

I've spent some time to translate the JS scripts to a typescript/webpack project.

The typescript sources can be compiled by running `npm install` in `frontend/` directory. The JS output is placed in the usual `/askomics/static` directory.

I kept the code editions to the minimal working set, to be able to move the files if you prefer another organization.
This is not finished work, I opened the PR for discussion.
## Benefits :
- webpack :
  - all 3rd party libraries are now downloaded with npm,
  - module hierarchy with static dependencies analysis,
  - Bundling : only two `<script>` tags required for all modules,
  - possibility to transform and prepare other static assets (bootstrap.css from the npm package, less/sass->css, combine css, compile handlebars templates)...
- typescript :
  - Type system describing the _shape_ of JS's objects,
  - _InteliSense_ in atom with `atom-typescript` : inferred type on hover, and go to definition/declaration/usages,
  - Only a static checker, the JS code is left mostly untouched (Transpiles ES6+ to ES5 -or even lower, strips types)
  - supports JSX syntax, and thus React,
  - `"use strict"` everywhere.
## WIP State
- a npm package running webpack on `npm install`,
- all classes/global singletons (_e.g._ `AskomicsGraphBuilder`) are rewritten as modules (see bellow) 
- minimization of the number of exported values,
- modules require explicitly each other,
- all the jQuery/Blueimp/Bootstrap JS is bundled with webpack
- **lots** of type errors to be corrected (where the inference can't follow).

In order to easily merge this PR, function blocks are left mostly unedited, a re-flow of indentation will be needed.
## Why I converted the classes to modules ?

Because `Askomics*` instances are used as namespaces :
- they are all instantiated as singletons,
- they are mostly "utility classes" and doesn't represents a particular datum,
- most methods don't read/write the instance (static methods).

Proof : It was easy to convert them to modules with `sed`, maintaining most of the functionality !

Moreover, they are malformed JS classes. Each time a new instance is created, the prototype methods of the class ( are all updated to function closing over the last instance's constructor local scope. _i.e._ all method call on all instances use the last instance's private variables.

``` js
// Correct :
function MyClass(v) { this.private_value = v; }
MyClass.prototype.getValue = function() { return this.private_value; }

// Askomics way (bad) :
function MyClass(v) {
  var private_value = v;
  // At every instantiation we reassign a closure on the constructor scope:
  MyClass.prototype.getValue = function() { return private_value; }
}
var a = new MyClass(1);
new MyClass(2);
a.getValue() == 2;
```

It's fine for singletons, but you still get a strange behavior...

The ES6 syntax is not as ambiguous :

``` ts
// ES6 clas syntax : Limpid !
class MyClass {
  constructor(v) { this.value = v; }
  getValue() { return this.value; }
}

// With types and genericity (compile down to the same JS than above)
class MyClass<T> {
  private value: T;
  constructor(v : T) { this.value = v; }
  getValue() : T { return this.value; }
}
```
### Refactoring

I think that, for now, modules are doing a great job for organizing the code and holding global state. We can gain more flexibility by keeping the business and utility code as independent module functions, they are more easy to move around. Since they have types, they remains related to the shape of data they accepts and produces. Plain old JS functions seems flapping in the breeze, because one needs to read the code to see on what kind of data it operates.

This PR reorganizes the code as modules of functions, some of which are closures on hidden module states. From there, the refactoring can be guided by the types of state variables : once we refine what they are, we can define what operations they accepts.
### TBD
- extensive checks for regressions,
- write interfaces for all the Node[View]/Link[View]/etc data shapes
- Encapsulate global state, (_e.g._ with an observable API)
- correct type errors, write more specific types, rinse, repeat
- Node.js/PhantomJS testing framework,
- style sheets building,
- optimize bundle size,
- rewrite views in React, drop jQuery (in my dreams).

### CODE REVIEW

**Comment by ofilangi** [comment]
Hello Piezoid.
Thx a lot for this impressive work !
However, I'm not agree with your organisation module. 
It's right, all classes are singleton for now but should be change to organize specific node (as GO) and specific link (positionable) as a inheritance of a general node/link.
I begin to change the classes with the ES6 syntax (but you don't let me the time to do a new PR). Thx a lot too for your explanation of use of 'var' inside a prototype class.
We are definitively interested with your integration of webpack but not necessary typescripts. We use now Grunt to check with jshint, minimize, uglify and execute test and, for instance, we do not plane to use JSX/React framework.
Olivier

**Comment by Piezoid** [comment]
Webpack over grunt brings module dependencies resolution and code hot loading. We can still use grunt as a task launcher for test cie.

I flattened the classes because I wanted to refactor the organization on a cleaner and more minimal type hierarchy. Typescript is a great help for that, it also brings type safety.
The typescript's compile process only strip types after verification, the code transformation is a simple ES6+ -> ES5 transpilation.

I've rebased this PR on your personal branches. Seems to work fine too, you can merge yours and deal with this PR latter.

But I'm worried of the direction taken with jQuery. It will not be manageable to update the view with jQuery without a properly decoupled MVC approach. The code is already bloated with removeOld->addNew->update steps. What isomorphic view frameworks (like React) brings is a simple process that rewrite html from data on changes.

**Comment by ofilangi** [comment]
"Webpack over grunt brings module dependencies resolution and code hot loading. We can still use grunt as a task launcher for test cie."
Yes, we agree !
"I flattened the classes because I wanted to refactor the organization on a cleaner and more minimal type hierarchy. Typescript is a great help for that, it also brings type safety.
The typescript's compile process only strip types after verification, the code transformation is a simple ES6+ -> ES5 transpilation."
Typescript implement class (interface, accessor public, private, etc...) paradigm. I 'm agree with the potential of typescript and the integration in askomics. but I want keep a class structure (singleton or not) on the project !

"I've rebased this PR on your personal branches. Seems to work fine too, you can merge yours and deal with this PR latter."
ok, on y side, I wil do a PR about Grunt additional files....

**Comment by Piezoid** [comment]
Ok thank you for your remarks.

I like better the new classes design on your forks (even if transparents getter/setter without validation are pointless...).

I have some question about the paths organization : 
 * On your fork you have created the npm package with grunt config in the repos root and left the `.js` in `.askomics/static/js` and output is emitted at `/askomics/static/dist/` ( or `/dist/`  ? I'm not sure)
* I have moved the `.js` in `/frontend/js/`  and the build output dir is `/askomics/static/js`

Personally I think the repo's root is crowded enough and the js package should go in a subdirectory (but not as deep as `/askomics/static/js`). And `/askomics/static/` should contain only Webpack generated files.
I'ts only my personal view point, but we should settle on a organization somehow.

If we use webpack we don't really needs Grunt. Webpack have file watching functionality (we needs to use it because it cache compilation for faster dev cycles) and can even run the linter (tslint/jslint) on the sources. Anyway, i plan to integrate Webpack tasks in the Gruntfile for now, once you have merged your changes. Functionality wise : 

 * Grunt is a modular task runner
 * Webpack is a specialized make like pipeline
 * [npm is a simple task runner](https://medium.freecodecamp.com/why-i-left-gulp-and-grunt-for-npm-scripts-3d6853dd22b8#.9t1i9cav6)

**Comment by ofilangi** [comment]
Le 12/07/2016 15:48, Maël Kerbiriou a écrit :
>
> Ok thank you for your remarks.
>
> I like better the new classes design on your forks (even if 
> transparents getter/setter without validation are pointless...).
>
I prefere too, but i miss time to improve the model....sorry for the 
accessor
>
> I have some question about the paths organization :
>
>   * On your fork you have created the npm package with grunt config in
>     the repos root and left the |.js| in |.askomics/static/js| and
>     output is emitted at |/askomics/static/dist/| ( or |/dist/| ? I'm
>     not sure)
>       o I have moved the |.js| in |/frontend/js/| and the build output
>         dir is |/askomics/static/js|
>
|good ! I'm not work a lot about this...it 's under construction....|
>
>  *
>      o
>
> Personally I think the repo's root is crowded enough and the js 
> package should go in a subdirectory (but not as deep as 
> |/askomics/static/js|). And |/askomics/static/| should contain only 
> Webpack generated files.
> I'ts only my personal view point, but we should settle on a 
> organization somehow.
>
> If we use webpack we don't really needs Grunt. Webpack have file 
> watching functionality (we needs to use it because it cache 
> compilation for faster dev cycles) and can even run the linter 
> (tslint/jslint) on the sources. Anyway, i plan to integrate Webpack 
> tasks in the Gruntfile for now, once you have merged your changes. 
> Functionality wise :
>
thx a lot Piezoid. I try to merge soon!

**Pull request closed without merging**
