### PR TITLE
Update all INI entry with Environment variables

### PR DESCRIPTION
**Pull request by xgaia**
All ini entry can be updated with environment variables

Environment variables have to be like:
```bash
ASKOCONFIG_section_key=value
```
As variables can not have special characters, they have to be replaced according the following table: 

|character|replacement|
|---|---|
 :|\_colon\_|
|.|\_dot\_|
|-|\_hyphen\_|

examples:

```bash
export ASKOCONFIG_app_colon_main_filter_hyphen_with="proxy-prefix"
export ASKOCONFIG_filter_colon_proxyprefix_use="egg:PasteDeploy#prefix"
export ASKOCONFIG_filter_colon_proxyprefix_prefix="/gie_proxy/askomics"
```

Will create in the ini file:
```ini
[app:main]
filter-with = proxy-prefix
[filter:proxyprefix]
use = egg:PasteDeploy#prefix
prefix = /gie_proxy/askomics
```

This change is needed for the Galaxy Virtual environment.

**EDIT:**

We keep the old way to manage config env variables:
```bash
ASKO_key=value
```
for 

```ini
[app:main]
askomics.key = value
```
and
```bash
ASKOCONFIG_section_key=value
```
for

```ini
[section]
key = value
```

### CODE REVIEW

**Comment by abretaud** [comment]
Just a suggestion (that you can reject!): I fear that it will become unreadable even for simple settings.
Would it be possible to keep the current syntax for *standard* config keys, but use this syntax for more complicated ones like filters? Maybe with a different env name prefix or by checking if it contains colon?

**Comment by xgaia** [comment]
Maybe it's a good idea, because lot of things use the old way to manage environment variables (all the docker-compose for exemple)

So I can keep the old way and add a new keyword for the new way like:

```bash
export ASKOINICONFIG_blablabla
```

**Comment by abretaud** [comment]
Sounds good! 👍 
(ASKOHARDCORECONFIG?)

**Comment by ofilangi** [comment]
:+1: to keep the "old" functionnality !

**Comment by xgaia** [comment]
hello everybody,

I'm done with this modifications,

Can I merge this PR and draft a 17.12 release to update the askomics/askomics-ie docker images ?

**Comment by ofilangi** [comment]
:+1:

**Pull request merged**
