### PR TITLE
Repair startService.sh

### PR DESCRIPTION
**Pull request by abretaud**
Fix startService.sh which got broken after latest changes to setup process
@Piezoid can you have a look at this?

### CODE REVIEW

**Comment by Piezoid** [comment]
It looks fine. @xgaia got some problems with the new script. Maybe we should wait for more details before copying it in startService.sh ?

I don't know Docker at all but have two (maybe naïve) remarks :
 * `sudo` can be avoided by [using a `docker` UNIX group](https://docs.docker.com/engine/installation/linux/debian/#giving-non-root-access)
 * Shouldn't the script be run inside the docker image ? The usage of virtual env in `startVenv.sh` could be made optional and it could be used as an [ENTRYPOINT](https://docs.docker.com/engine/reference/builder/#entrypoint)

**Comment by xgaia** [comment]
Yes, i 've got an error when launching the startVenv script on my laptop yesterday (but i left it at home today ..) i will take a look this afternoon.

**Comment by xgaia** [comment]
On my Ubuntu 16.04:

    $ ./startVEnv.sh ./startVEnv.sh
    ./startVEnv.sh: 14: ./startVEnv.sh: Syntax error: word unexpected (expecting ")")

**Comment by Piezoid** [comment]
Some fixes needed on both script:

* Get python full path : `PYTHON=${PYTHON:-$(which python3)} `. (should be done a second time after entering the virtual environnement)
* run `python -m ensurepip` before creating the virtual environment
* Use python module invocation instead of wrapper scripts : `$PYTHON -m venv` instead of `venv`, and `$PYTHON -m pip` instead of `pip3`.

All of this needs to be run inside the docker image, so using a wrapper script as ENTRYPOINT makes more sense in my opinion. The `startService.sh`  starts side services depending on its argument, and then passes its arguments unchanged to the `startAskomics.sh --no-venv` (formerly `startVEnv.sh`) ENTRYPOINT in the docker.

I'll make a pull request when I get time to test docker images.

**Comment by abretaud** [comment]
Can you give a little more details on this please?
-is there a particular reason for using module invocation instead of wrapper scripts?
-I don't understand what is the "startAskomics.sh --no-venv" you're refering to, is this something you have written or that we should do?
Thanks!

**Comment by abretaud** [comment]
I reworked the scripts in this way, it seems to work now
As askomics is currently broken, I merge this to make it usable

**Comment by Piezoid** [comment]
I think you forgot to do `git mv`, `startAskomics.sh` doesn't exists

**Pull request merged**
